In [1]:
import numpy as np
import pandas as pd

In [5]:
cols = ['reviewerID', 'asin', 'overall', 'unixReviewTime']
dataset_songs = pd.read_csv("data/ratings_Digital_Music.csv", names=cols)

In [6]:
dataset_songs.head()

       reviewerID        asin  overall  unixReviewTime
0  A2EFCYXHNK06IS  5555991584      5.0       978480000
1  A1WR23ER5HMAA9  5555991584      5.0       953424000
2  A2IR4Q0GPAFJKW  5555991584      4.0      1393545600
3  A2V0KUVAB9HSYO  5555991584      4.0       966124800
4  A1J0GL9HCA7ELW  5555991584      5.0      1007683200

In [7]:
dataset_songs.shape

(836006, 4)

In [8]:
songs_df = dataset_songs.head(10000)

In [9]:
from sklearn.model_selection import train_test_split
df_train, df_test = train_test_split(songs_df,test_size=0.2)

In [10]:
df_original_train = df_train.copy()
df_train = df_train.pivot(index = "asin" , columns = "reviewerID" , values = "overall")
df_train = df_train.sort_index(axis=1)

In [11]:
df_train.head()

reviewerID,A07465992K7FVSL53VA9B,A08161909WK3HU7UYTMW,A086594320Z777EHOFWKU,A102VKCQOZD2C,A102X8CNVNLINY,A10323WWTFPSGP,A103W7ZPKGOCC9,A103YTM9ARROO3,A104ID0XLCHNGH,A10587XDOY3OR0,...,AZTMY41RFNJR9,AZUJG3MINZITV,AZULSERA2QLEA,AZUQI0LIRM7DH,AZUS7IMHG0J22,AZVA13Q19KURR,AZVHFS4KQBQTK,AZWPUN8MCHJQW,AZXZ6VOK6RPOM,AZZDB4I5INFON
asin,,,,,,,,,,,,,,,,,,,,,
5555991584,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6308051551,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7901622466,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B0000000ZW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B00000016T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
X = df_train.values
Y = df_train.sum(axis = 1)
Z =df_train.count(axis =1).astype('float64')
Y = Y.div(Z,axis=0)
#cosine
df_new_train = df_train.sub(Y,axis=0).fillna(0)

In [13]:
df_new_train.head()

reviewerID,A07465992K7FVSL53VA9B,A08161909WK3HU7UYTMW,A086594320Z777EHOFWKU,A102VKCQOZD2C,A102X8CNVNLINY,A10323WWTFPSGP,A103W7ZPKGOCC9,A103YTM9ARROO3,A104ID0XLCHNGH,A10587XDOY3OR0,...,AZTMY41RFNJR9,AZUJG3MINZITV,AZULSERA2QLEA,AZUQI0LIRM7DH,AZUS7IMHG0J22,AZVA13Q19KURR,AZVHFS4KQBQTK,AZWPUN8MCHJQW,AZXZ6VOK6RPOM,AZZDB4I5INFON
asin,,,,,,,,,,,,,,,,,,,,,
5555991584,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6308051551,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7901622466,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B0000000ZW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B00000016T,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
df = songs_df#dataset_songs
n_users = df.reviewerID.unique().shape[0]
n_items = df.asin.unique().shape[0]
print ( str(n_users) , ' users')
print ( str(n_items) , ' items')

8355  users
500  items

In [29]:
ratings = df_new_train
sparsity = float(ratings.astype(bool).sum(axis=0)[1])
sparsity /= (ratings.shape[0] * ratings.shape[1])
sparsity *= 100
print('Sparsity : ',sparsity)

Sparsity :  2.9612222030071802e-05

In [30]:
def train_test_split(ratings):
    test = np.zeros(ratings.shape)
    train = ratings.copy()
    for user in range(ratings.shape[0]):
        test_ratings = np.random.choice(ratings[0, :].nonzero()[0], 
                                        size=10, 
                                        replace=False)
        train[user, test_ratings] = 0.
        test[user, test_ratings] = ratings[user, test_ratings]
        
    # Test and training are truly disjoint
    assert(np.all((train * test) == 0)) 
    return train, test

In [31]:
train, test = train_test_split(ratings)

TypeError: unhashable type: 'slice'